### ISSUE TITLE
Switching shaders crashes, rendering issue

### ISSUE THREAD

**Issue by Kaoli5** [lucaargolo/lifts#39]
#Introduction
I want to preface this by saying from what I could gather this is a bug with the mod, and not with the shaders. I will further research and keep this issue updated.

Version: Lifts 1.4 BETA 1.18
Fabric Loader Version: 0.13.3
Shaders used: SEUS PTGI HRR 2.1 test

#Overview of Issue

When switching from either no shaders to shaders - or from shaders to no shaders, I have found a lot of the objects in the mod produce a crash. Currently, my issue is showing the "electric_lift_mk5" is causing the issue. After a bit of testing, I also noticed that other blocks (from testing; screens and wireless screen chargers) produced a similar issue, which seems to be related to an ArrayIndexOutOfBoundsException, which is trying to use index 72 out of a 32 int array.

#Mods used and Java Version
java: OpenJDK 64-Bit Server VM 17

exlinefurniture: Exline's Furniture fabric-1.18.1-v2.0.4
lifts: Lifts 1.4-BETA+1.18
mm: Manningham Mills 2.3
optifabric: OptiFabric 1.12.10
reborncore: Reborn Core 5.1.0
team_reborn_energy: Energy 2.2.0
techreborn: Tech Reborn 5.1.0
warp_mod_fabric: Warp Mod 0.0.1
worldedit: WorldEdit 7.2.9+e20e013

**__These mod lists are solely for the developer to analyze if it was their mod or just a conflict, please do not reply with a resolution. This will keep all the relevant technical information forefront, and it will prevent any unnecessary information.__**

#Stack Trace (Crash Report)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 72 out of bounds for int[32]
	at java.base/java.lang.System.arraycopy(Native Method)
	at net.fabricmc.fabric.impl.client.indigo.renderer.mesh.MutableQuadViewImpl.fromVanilla(MutableQuadViewImpl.java:108)
	at net.fabricmc.fabric.impl.client.indigo.renderer.mesh.MutableQuadViewImpl.fromVanilla(MutableQuadViewImpl.java:49)
	at io.github.lucaargolo.lifts.client.render.bakedmodel.screen.ElectricLiftBakedModel.emitFromVanilla(ElectricLiftBakedModel.kt:124)
	at io.github.lucaargolo.lifts.client.render.bakedmodel.screen.ElectricLiftBakedModel.emitBlockQuads(ElectricLiftBakedModel.kt:88)
	at io.github.lucaargolo.lifts.client.render.bakedmodel.screen.ElectricLiftBakedModel.emitItemQuads(ElectricLiftBakedModel.kt:76)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:117)
	at net.minecraft.class_918.handler$zfm000$hook_method_23179(class_918.java:557)
	at net.minecraft.class_918.method_23179(class_918.java)
	at net.minecraft.class_918.method_4021(class_918.java:443)
	at net.minecraft.class_918.method_4026(class_918.java:498)
	at net.minecraft.class_918.method_36543(class_918.java:486)
	at net.minecraft.class_918.method_27951(class_918.java:481)
	at net.minecraft.class_329.method_1762(class_329.java:1429)
	at net.minecraft.class_329.method_1759(class_329.java:689)
	at net.minecraft.class_329.method_1753(class_329.java:238)
	at net.minecraft.class_757.method_3192(class_757.java:1217)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

#Thread: Render thread stack trace
Stacktrace:
	at java.base/java.lang.System.arraycopy(Native Method)
	at net.fabricmc.fabric.impl.client.indigo.renderer.mesh.MutableQuadViewImpl.fromVanilla(MutableQuadViewImpl.java:108)
	at net.fabricmc.fabric.impl.client.indigo.renderer.mesh.MutableQuadViewImpl.fromVanilla(MutableQuadViewImpl.java:49)
	at io.github.lucaargolo.lifts.client.render.bakedmodel.screen.ElectricLiftBakedModel.emitFromVanilla(ElectricLiftBakedModel.kt:124)
	at io.github.lucaargolo.lifts.client.render.bakedmodel.screen.ElectricLiftBakedModel.emitBlockQuads(ElectricLiftBakedModel.kt:88)
	at io.github.lucaargolo.lifts.client.render.bakedmodel.screen.ElectricLiftBakedModel.emitItemQuads(ElectricLiftBakedModel.kt:76)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:117)
	at net.minecraft.class_918.handler$zfm000$hook_method_23179(class_918.java:557)
	at net.minecraft.class_918.method_23179(class_918.java)
	at net.minecraft.class_918.method_4021(class_918.java:443)
	at net.minecraft.class_918.method_4026(class_918.java:498)
	at net.minecraft.class_918.method_36543(class_918.java:486)
	at net.minecraft.class_918.method_27951(class_918.java:481)
	at net.minecraft.class_329.method_1762(class_329.java:1429)
	at net.minecraft.class_329.method_1759(class_329.java:689)
	at net.minecraft.class_329.method_1753(class_329.java:238)

#Item in question
-- Item being rendered --
Details:
	Item Type: electric_lift_mk5
	Registry Name: null
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.class_918.method_4026(class_918.java:498)
	at net.minecraft.class_918.method_36543(class_918.java:486)
	at net.minecraft.class_918.method_27951(class_918.java:481)
	at net.minecraft.class_329.method_1762(class_329.java:1429)
	at net.minecraft.class_329.method_1759(class_329.java:689)
	at net.minecraft.class_329.method_1753(class_329.java:238)
	at net.minecraft.class_757.method_3192(class_757.java:1217)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

#Closing information
Please bear with me, as I am a python developer and do not usually dabble in Java. If there is anything anyone would like to review, please reply to this bug report. I could easily be completely wrong and it could probably be something I might have done or a conflict in my mods.

As for my further actions, I will continue to test and attempt to find a solution, if possible.

Furthermore, I have included the entire report in an attachment
[crash-2022-03-19_20.15.47-client.txt](https://github.com/lucaargolo/lifts/files/8310387/crash-2022-03-19_20.15.47-client.txt)
.

**Comment by Kaoli5** [comment]
Update:

Further Testing and possible fix implementations did not succeed. The issue is still present, but I believe it might be the shaders used in combination with the computer hardware.

Specs:

AMD Ryzen 5 2600
16Gb DDR4 3200 Memory (G.Skill Trident) (BIOS Configured)
XFX Radeon RX 580 4GB
Baseboard: ROG Strix B450F Gaming II
